### ISSUE TITLE
react 0.12 - missing layoutContext 

### ISSUE THREAD

**Issue by mxaly** [jsdf/react-layout#2]
Is this compatible with react 0.12? i'm getting `missing layoutContext` error

**Comment by jsdf** [comment]
Can you give me an example of your code?

**Comment by jsdf** [comment]
Actually I found a bug which was most likely the cause of the error you're seeing, please try the new version which I have published to npm. Thanks.

**Comment by joewood** [comment]
I don't see an update in npm, and I'm getting the same error. Has this been fixed?

**Comment by jsdf** [comment]
Oops. Try getting v0.2.0 from npm now.
