### ISSUE TITLE
LayoutMixin

### ISSUE THREAD

**Issue by pedroteixeira** [jsdf/react-layout#4]
Hi, is there any example of spliting the layout into different nested components?

For some reason, when trying to extract layout from a single component into child components, I'm getting `Error: missing layoutContext.height`  (react 0.12.2), for some reason layoutContext is not being propageted. Any hints?

thanks.

**Comment by pedroteixeira** [comment]
never mind.. it seems to be working as expected.

**Comment by amitkmehra** [comment]
i am also getting the same error anybody have any idea on how to resolve it

**Comment by pedroteixeira** [comment]
I guess one way is in the component you use `LayoutMixin`, you can render `( <Layout> .. </Layout> )` and props such as `layoutWidth`, `layoutHeight` can be passed to your custom component (the one with the mixin).
