### ISSUE TITLE
demo:build failed if example/build doesn't exist

### ISSUE THREAD

**Issue by ycdesu** [jsdf/react-layout#8]
hi, I execute `npm run demo:build` and get an error if `example/build` doesn't exist. I add `mkdir` to it. Here's the code: `"demo:build": "mkdir -p example/build && browserifyinc -t babelify example/index.js --cachefile example/build/cache.json >  example/build/bundle.js"`. Thanks.

**Comment by jsdf** [comment]
Fixed
